remove use of C++17 code as it currently not works with nlohmann-json
Strange part is, if library compiled with C++14 and addon with C++17 it works.
Only if both compiled with C++17 it fails.

As it works with old code style becomes here the "#if __cplusplus >= 201703L" removed on related places.

Errors relates to this code:
```cpp
for (auto & [id, quality] = d.items ())
```

And produce this as error (here if "const auto &" was used):

```
[ 50%] Building CXX object CMakeFiles/pvr.freebox.dir/src/Freebox.cpp.o
/home/alwin/Development/Kodi/_Addons/_alwin/pvr/pvr.freebox/src/Freebox.cpp: In member function ‘bool Freebox::ProcessChannels()’:
/home/alwin/Development/Kodi/_Addons/_alwin/pvr/pvr.freebox/src/Freebox.cpp:889:25: error: cannot decompose inaccessible member ‘nlohmann::detail::iteration_proxy<nlohmann::detail::iter_impl<nlohmann::basic_json<> > >::container’ of ‘const nlohmann::detail::iteration_proxy<nlohmann::detail::iter_impl<nlohmann::basic_json<> > >’
  889 |       for (const auto & [id, quality] = d.items ())
      |                         ^~~~~~~~~~~~~
In file included from /home/alwin/Development/Kodi/_Addons/_alwin/pvr/pvr.freebox/src/Freebox.h:27,
                 from /home/alwin/Development/Kodi/_Addons/_alwin/pvr/pvr.freebox/src/Freebox.cpp:39:
/home/alwin/Development/Kodi/_Addons/_alwin/pvr/pvr.freebox/build/build/depends/include/kodi/../nlohmann/json.hpp:4474:38: note: declared private here
 4474 |     typename IteratorType::reference container;
      |                                      ^~~~~~~~~
/home/alwin/Development/Kodi/_Addons/_alwin/pvr/pvr.freebox/src/Freebox.cpp:889:51: error: expected ‘;’ before ‘)’ token
  889 |       for (const auto & [id, quality] = d.items ())
      |                                                   ^
      |                                                   ;
/home/alwin/Development/Kodi/_Addons/_alwin/pvr/pvr.freebox/src/Freebox.cpp:889:51: error: expected primary-expression before ‘)’ token
/home/alwin/Development/Kodi/_Addons/_alwin/pvr/pvr.freebox/src/Freebox.cpp:889:51: error: expected ‘;’ before ‘)’ token
  889 |       for (const auto & [id, quality] = d.items ())
      |                                                   ^
      |                                                   ;
make[5]: *** [CMakeFiles/pvr.freebox.dir/build.make:63: CMakeFiles/pvr.freebox.dir/src/Freebox.cpp.o] Fehler 1
make[4]: *** [CMakeFiles/Makefile2:77: CMakeFiles/pvr.freebox.dir/all] Fehler 2
make[3]: *** [Makefile:152: all] Fehler 2
make[2]: *** [CMakeFiles/pvr.freebox.dir/build.make:114: pvr.freebox-prefix/src/pvr.freebox-stamp/pvr.freebox-build] Fehler 2
make[1]: *** [CMakeFiles/Makefile2:270: CMakeFiles/pvr.freebox.dir/all] Fehler 2
make: *** [Makefile:84: all] Fehler 2
```